-- =============================================================================
-- METGO — Actualizar / alinear tablas meteorológicas en Supabase
-- Ejecutar en: SQL Editor → New query → Run
-- Seguro de re-ejecutar (idempotente): CREATE IF NOT EXISTS + ADD COLUMN IF NOT EXISTS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1) meteo_registros (histórico observado / Archive) — suele existir ya
-- ---------------------------------------------------------------------------
create table if not exists public.meteo_registros (
    id bigint generated by default as identity primary key,
    estacion_id text not null,
    fecha date not null,
    temperatura_max double precision,
    temperatura_min double precision,
    temperatura_promedio double precision,
    humedad double precision,
    precipitacion double precision,
    viento double precision,
    presion double precision,
    cobertura_nubosa double precision,
    visibilidad double precision,
    radiacion double precision,
    evapotranspiracion double precision,
    helada boolean,
    niebla boolean,
    fuente text default 'openmeteo',
    creado_en timestamptz default now(),
    unique (estacion_id, fecha)
);

-- Columnas que pueden faltar en una tabla creada con anterioridad
alter table public.meteo_registros add column if not exists temperatura_max double precision;
alter table public.meteo_registros add column if not exists temperatura_min double precision;
alter table public.meteo_registros add column if not exists temperatura_promedio double precision;
alter table public.meteo_registros add column if not exists humedad double precision;
alter table public.meteo_registros add column if not exists precipitacion double precision;
alter table public.meteo_registros add column if not exists viento double precision;
alter table public.meteo_registros add column if not exists presion double precision;
alter table public.meteo_registros add column if not exists cobertura_nubosa double precision;
alter table public.meteo_registros add column if not exists visibilidad double precision;
alter table public.meteo_registros add column if not exists radiacion double precision;
alter table public.meteo_registros add column if not exists evapotranspiracion double precision;
alter table public.meteo_registros add column if not exists helada boolean;
alter table public.meteo_registros add column if not exists niebla boolean;
alter table public.meteo_registros add column if not exists fuente text;
alter table public.meteo_registros add column if not exists creado_en timestamptz default now();

-- Unique (estacion_id, fecha) si aún no existe
do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'meteo_registros_estacion_id_fecha_key'
          and conrelid = 'public.meteo_registros'::regclass
    ) then
        alter table public.meteo_registros
            add constraint meteo_registros_estacion_id_fecha_key unique (estacion_id, fecha);
    end if;
exception when others then
    -- Si ya hay otro unique equivalente, no fallar el script
    raise notice 'meteo_registros unique: %', sqlerrm;
end $$;

create index if not exists idx_meteo_registros_estacion_fecha
    on public.meteo_registros (estacion_id, fecha desc);

create index if not exists idx_meteo_registros_fuente
    on public.meteo_registros (fuente);

-- ---------------------------------------------------------------------------
-- 2) meteo_pronostico (pronóstico diario)
-- ---------------------------------------------------------------------------
create table if not exists public.meteo_pronostico (
    id bigint generated by default as identity primary key,
    estacion_id text not null,
    fecha date not null,
    temperatura_max double precision,
    temperatura_min double precision,
    temperatura_promedio double precision,
    humedad double precision,
    precipitacion double precision,
    probabilidad_lluvia double precision,
    viento double precision,
    direccion_viento double precision,
    presion double precision,
    cobertura_nubosa double precision,
    visibilidad double precision,
    radiacion double precision,
    fuente text default 'openmeteo_pronostico',
    actualizado text,
    creado_en timestamptz default now(),
    unique (estacion_id, fecha)
);

alter table public.meteo_pronostico add column if not exists temperatura_max double precision;
alter table public.meteo_pronostico add column if not exists temperatura_min double precision;
alter table public.meteo_pronostico add column if not exists temperatura_promedio double precision;
alter table public.meteo_pronostico add column if not exists humedad double precision;
alter table public.meteo_pronostico add column if not exists precipitacion double precision;
alter table public.meteo_pronostico add column if not exists probabilidad_lluvia double precision;
alter table public.meteo_pronostico add column if not exists viento double precision;
alter table public.meteo_pronostico add column if not exists direccion_viento double precision;
alter table public.meteo_pronostico add column if not exists presion double precision;
alter table public.meteo_pronostico add column if not exists cobertura_nubosa double precision;
alter table public.meteo_pronostico add column if not exists visibilidad double precision;
alter table public.meteo_pronostico add column if not exists radiacion double precision;
alter table public.meteo_pronostico add column if not exists fuente text;
alter table public.meteo_pronostico add column if not exists actualizado text;
alter table public.meteo_pronostico add column if not exists creado_en timestamptz default now();

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'meteo_pronostico_estacion_id_fecha_key'
          and conrelid = 'public.meteo_pronostico'::regclass
    ) then
        alter table public.meteo_pronostico
            add constraint meteo_pronostico_estacion_id_fecha_key unique (estacion_id, fecha);
    end if;
exception when others then
    raise notice 'meteo_pronostico unique: %', sqlerrm;
end $$;

create index if not exists idx_meteo_pronostico_estacion_fecha
    on public.meteo_pronostico (estacion_id, fecha desc);

-- ---------------------------------------------------------------------------
-- 3) meteo_series (JSON: viento horario, precip 3h, etc.)
-- ---------------------------------------------------------------------------
create table if not exists public.meteo_series (
    id bigint generated by default as identity primary key,
    estacion_id text not null,
    tipo text not null,
    payload jsonb not null,
    actualizado timestamptz default now(),
    unique (estacion_id, tipo)
);

alter table public.meteo_series add column if not exists payload jsonb;
alter table public.meteo_series add column if not exists actualizado timestamptz default now();

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'meteo_series_estacion_id_tipo_key'
          and conrelid = 'public.meteo_series'::regclass
    ) then
        alter table public.meteo_series
            add constraint meteo_series_estacion_id_tipo_key unique (estacion_id, tipo);
    end if;
exception when others then
    raise notice 'meteo_series unique: %', sqlerrm;
end $$;

create index if not exists idx_meteo_series_estacion_tipo
    on public.meteo_series (estacion_id, tipo);

-- ---------------------------------------------------------------------------
-- 4) Permisos (corrige "permission denied" / 42501)
-- ---------------------------------------------------------------------------
grant usage on schema public to anon, authenticated, service_role;

grant select, insert, update, delete on public.meteo_registros  to service_role;
grant select, insert, update, delete on public.meteo_pronostico to service_role;
grant select, insert, update, delete on public.meteo_series     to service_role;

grant usage, select on all sequences in schema public to service_role;

grant select on public.meteo_registros  to anon, authenticated;
grant select on public.meteo_pronostico to anon, authenticated;
grant select on public.meteo_series     to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5) RLS (lectura pública; escritura solo service_role, que bypasea RLS)
-- ---------------------------------------------------------------------------
alter table public.meteo_registros  enable row level security;
alter table public.meteo_pronostico enable row level security;
alter table public.meteo_series     enable row level security;

drop policy if exists meteo_registros_lectura  on public.meteo_registros;
drop policy if exists meteo_pronostico_lectura on public.meteo_pronostico;
drop policy if exists meteo_series_lectura     on public.meteo_series;

create policy meteo_registros_lectura  on public.meteo_registros  for select using (true);
create policy meteo_pronostico_lectura on public.meteo_pronostico for select using (true);
create policy meteo_series_lectura     on public.meteo_series     for select using (true);

-- ---------------------------------------------------------------------------
-- 6) meteo_helada_pronostico — resultado del modelo radiativo + psicrómetro
--    (insumos diarios viven en meteo_pronostico; aquí va la identificación)
-- ---------------------------------------------------------------------------
create table if not exists public.meteo_helada_pronostico (
    id bigint generated by default as identity primary key,
    estacion_id text not null,
    fecha date not null,
    cultivo text not null default 'palto',
    probabilidad_helada double precision,
    nivel_riesgo text,
    riesgo_severo boolean,
    riesgo_moderado boolean,
    riesgo_inminente boolean,
    temperatura_minima_esperada double precision,
    temperatura_maxima double precision,
    temperatura_atardecer double precision,
    punto_rocio_atardecer double precision,
    bulbo_humedo_atardecer double precision,
    humedad_relativa double precision,
    cobertura_nubosa double precision,
    velocidad_viento double precision,
    umbral_cultivo double precision,
    alerta_cultivo boolean,
    hora_critica_esperada text default '04:00',
    criterio_psicrometro jsonb,
    scores_componentes jsonb,
    factores_contribuyentes jsonb,
    recomendaciones jsonb,
    fuente text default 'modelo_helada_radiativa',
    actualizado timestamptz default now(),
    unique (estacion_id, fecha, cultivo)
);

alter table public.meteo_helada_pronostico add column if not exists cultivo text;
alter table public.meteo_helada_pronostico add column if not exists probabilidad_helada double precision;
alter table public.meteo_helada_pronostico add column if not exists nivel_riesgo text;
alter table public.meteo_helada_pronostico add column if not exists riesgo_severo boolean;
alter table public.meteo_helada_pronostico add column if not exists riesgo_moderado boolean;
alter table public.meteo_helada_pronostico add column if not exists riesgo_inminente boolean;
alter table public.meteo_helada_pronostico add column if not exists temperatura_minima_esperada double precision;
alter table public.meteo_helada_pronostico add column if not exists temperatura_maxima double precision;
alter table public.meteo_helada_pronostico add column if not exists temperatura_atardecer double precision;
alter table public.meteo_helada_pronostico add column if not exists punto_rocio_atardecer double precision;
alter table public.meteo_helada_pronostico add column if not exists bulbo_humedo_atardecer double precision;
alter table public.meteo_helada_pronostico add column if not exists humedad_relativa double precision;
alter table public.meteo_helada_pronostico add column if not exists cobertura_nubosa double precision;
alter table public.meteo_helada_pronostico add column if not exists velocidad_viento double precision;
alter table public.meteo_helada_pronostico add column if not exists umbral_cultivo double precision;
alter table public.meteo_helada_pronostico add column if not exists alerta_cultivo boolean;
alter table public.meteo_helada_pronostico add column if not exists hora_critica_esperada text;
alter table public.meteo_helada_pronostico add column if not exists criterio_psicrometro jsonb;
alter table public.meteo_helada_pronostico add column if not exists scores_componentes jsonb;
alter table public.meteo_helada_pronostico add column if not exists factores_contribuyentes jsonb;
alter table public.meteo_helada_pronostico add column if not exists recomendaciones jsonb;
alter table public.meteo_helada_pronostico add column if not exists fuente text;
alter table public.meteo_helada_pronostico add column if not exists actualizado timestamptz default now();

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'meteo_helada_pronostico_estacion_id_fecha_cultivo_key'
          and conrelid = 'public.meteo_helada_pronostico'::regclass
    ) then
        alter table public.meteo_helada_pronostico
            add constraint meteo_helada_pronostico_estacion_id_fecha_cultivo_key
            unique (estacion_id, fecha, cultivo);
    end if;
exception when others then
    raise notice 'meteo_helada_pronostico unique: %', sqlerrm;
end $$;

create index if not exists idx_meteo_helada_estacion_fecha
    on public.meteo_helada_pronostico (estacion_id, fecha desc);

create index if not exists idx_meteo_helada_nivel
    on public.meteo_helada_pronostico (nivel_riesgo);

grant select, insert, update, delete on public.meteo_helada_pronostico to service_role;
grant select on public.meteo_helada_pronostico to anon, authenticated;

alter table public.meteo_helada_pronostico enable row level security;

drop policy if exists meteo_helada_pronostico_lectura on public.meteo_helada_pronostico;
create policy meteo_helada_pronostico_lectura
    on public.meteo_helada_pronostico for select using (true);

-- ---------------------------------------------------------------------------
-- 7) Verificación rápida (opcional): debe listar las 4 tablas
-- ---------------------------------------------------------------------------
-- select table_name
-- from information_schema.tables
-- where table_schema = 'public'
--   and table_name in (
--     'meteo_registros', 'meteo_pronostico', 'meteo_series', 'meteo_helada_pronostico'
--   );
