@echo off
echo Activando entorno virtual METGO 3D...
call "D:\METGO_3D_Quillota_60GB\metgo_env\Scripts\activate.bat"
echo Entorno activado. Ejecutando sistema...
python sistema_unificado_con_conectores.py
