#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Catálogo SPATI — 17 mineras alta montaña Chile + demos METGO.

z₀, zona climática y tipo eólico según módulo Alta Montaña SPATI.
Coordenadas WGS84 desde DMS operativos. Densidad ρ vía HighAltitudeEngine.
"""

from __future__ import annotations

from typing import Any

# slug → sitio grúa (z0 del spec Alta Montaña)
SITIOS_GRUA: dict[str, dict[str, Any]] = {
    "quebrada_blanca": {
        "sitio_id": "quebrada_blanca",
        "nombre": "Quebrada Blanca",
        "region": "Tarapacá",
        "operador": "Teck Resources",
        "lat": -21.000000,
        "lon": -68.816667,
        "altitud_msnm": 4400,
        "altura_pluma_m": 55,
        "z0_terreno": 0.25,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "quebrada_cordillera",
        "zona_climatica": "altiplano",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "collahuasi": {
        "sitio_id": "collahuasi",
        "nombre": "Collahuasi",
        "region": "Tarapacá",
        "operador": "Compañía Minera Doña Inés de Collahuasi",
        "lat": -20.964167,
        "lon": -68.661111,
        "altitud_msnm": 4200,
        "altura_pluma_m": 55,
        "z0_terreno": 0.20,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "altiplano",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "cerro_colorado": {
        "sitio_id": "cerro_colorado",
        "nombre": "Cerro Colorado",
        "region": "Tarapacá",
        "operador": "BHP",
        "lat": -20.059444,
        "lon": -69.270000,
        "altitud_msnm": 2600,
        "altura_pluma_m": 55,
        "z0_terreno": 0.10,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "precordillera",
        "riesgo_eolico": "alto",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "el_abra": {
        "sitio_id": "el_abra",
        "nombre": "El Abra",
        "region": "Antofagasta",
        "operador": "Freeport-McMoRan",
        "lat": -21.920556,
        "lon": -68.832222,
        "altitud_msnm": 4005,
        "altura_pluma_m": 55,
        "z0_terreno": 0.22,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "altiplano",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "chuquicamata": {
        "sitio_id": "chuquicamata",
        "nombre": "Chuquicamata",
        "region": "Antofagasta",
        "operador": "Codelco",
        "lat": -22.290556,
        "lon": -68.901944,
        "altitud_msnm": 2860,
        "altura_pluma_m": 55,
        "z0_terreno": 0.35,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "altiplano",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "radomiro_tomic": {
        "sitio_id": "radomiro_tomic",
        "nombre": "Radomiro Tomic",
        "region": "Antofagasta",
        "operador": "Codelco",
        "lat": -22.216667,
        "lon": -68.900000,
        "altitud_msnm": 2950,
        "altura_pluma_m": 55,
        "z0_terreno": 0.15,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "precordillera",
        "riesgo_eolico": "alto",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "ministro_hales": {
        "sitio_id": "ministro_hales",
        "nombre": "Ministro Hales",
        "region": "Antofagasta",
        "operador": "Codelco",
        "lat": -22.381667,
        "lon": -68.912222,
        "altitud_msnm": 2600,
        "altura_pluma_m": 55,
        "z0_terreno": 0.20,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "precordillera",
        "riesgo_eolico": "alto",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "spence": {
        "sitio_id": "spence",
        "nombre": "Spence",
        "region": "Antofagasta",
        "operador": "BHP",
        "lat": -22.795556,
        "lon": -69.253333,
        "altitud_msnm": 1725,
        "altura_pluma_m": 55,
        "z0_terreno": 0.05,
        "tipo_terreno": "llano_semiarido",
        "tipo_terreno_eolico": "superficie_plana",
        "zona_climatica": "precordillera",
        "riesgo_eolico": "moderado",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "escondida": {
        "sitio_id": "escondida",
        "nombre": "Escondida",
        "region": "Antofagasta",
        "operador": "BHP",
        "lat": -24.251667,
        "lon": -69.054167,
        "altitud_msnm": 3075,
        "altura_pluma_m": 55,
        "z0_terreno": 0.25,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "altiplano",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "el_penon": {
        "sitio_id": "el_penon",
        "nombre": "El Peñón",
        "region": "Antofagasta",
        "operador": "Yamana Gold",
        "lat": -24.410833,
        "lon": -69.496111,
        "altitud_msnm": 2200,
        "altura_pluma_m": 45,
        "z0_terreno": 0.15,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "precordillera",
        "riesgo_eolico": "moderado",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 10.0,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 20000,
        "nota_altitud": "altitud no publicada; valor estimado operativo",
    },
    "la_coipa": {
        "sitio_id": "la_coipa",
        "nombre": "La Coipa",
        "region": "Atacama",
        "operador": "Kinross Gold",
        "lat": -26.699722,
        "lon": -69.500000,
        "altitud_msnm": 4000,
        "altura_pluma_m": 55,
        "z0_terreno": 0.18,
        "tipo_terreno": "valle_cordillera",
        "tipo_terreno_eolico": "quebrada_cordillera",
        "zona_climatica": "precordillera",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "maricunga": {
        "sitio_id": "maricunga",
        "nombre": "Maricunga",
        "region": "Atacama",
        "operador": "Kinross Gold",
        "lat": -27.533333,
        "lon": -69.300000,
        "altitud_msnm": 4300,
        "altura_pluma_m": 55,
        "z0_terreno": 0.05,
        "tipo_terreno": "llano_semiarido",
        "tipo_terreno_eolico": "terreno_abierto",
        "zona_climatica": "altiplano",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "candelaria": {
        "sitio_id": "candelaria",
        "nombre": "Candelaria",
        "region": "Atacama",
        "operador": "Lundin Mining",
        "lat": -27.509722,
        "lon": -70.287500,
        "altitud_msnm": 729,
        "altura_pluma_m": 55,
        "z0_terreno": 0.05,
        "tipo_terreno": "costero_abierto",
        "tipo_terreno_eolico": "superficie_plana",
        "zona_climatica": "costero",
        "riesgo_eolico": "bajo",
        "requiere_autorizacion_dgac": False,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "los_pelambres": {
        "sitio_id": "los_pelambres",
        "nombre": "Los Pelambres",
        "region": "Coquimbo",
        "operador": "Antofagasta Minerals",
        "lat": -31.716667,
        "lon": -70.490556,
        "altitud_msnm": 3600,
        "altura_pluma_m": 55,
        "z0_terreno": 0.30,
        "tipo_terreno": "valle_cordillera",
        "tipo_terreno_eolico": "quebrada_cordillera",
        "zona_climatica": "andes_central",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "los_bronces": {
        "sitio_id": "los_bronces",
        "nombre": "Los Bronces",
        "region": "Metropolitana",
        "operador": "Anglo American",
        "lat": -33.150278,
        "lon": -70.287222,
        "altitud_msnm": 3500,
        "altura_pluma_m": 55,
        "z0_terreno": 0.35,
        "tipo_terreno": "valle_cordillera",
        "tipo_terreno_eolico": "quebrada_cordillera",
        "zona_climatica": "andes_central",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "andina": {
        "sitio_id": "andina",
        "nombre": "Andina",
        "region": "Valparaíso",
        "operador": "Codelco",
        "lat": -33.061389,
        "lon": -70.250278,
        "altitud_msnm": 3950,
        "altura_pluma_m": 55,
        "z0_terreno": 0.40,
        "tipo_terreno": "valle_cordillera",
        "tipo_terreno_eolico": "quebrada_cordillera",
        "zona_climatica": "andes_central",
        "riesgo_eolico": "extremo",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "el_teniente": {
        "sitio_id": "el_teniente",
        "nombre": "El Teniente",
        "region": "O'Higgins",
        "operador": "Codelco",
        "lat": -34.094167,
        "lon": -70.350833,
        "altitud_msnm": 2300,
        "altura_pluma_m": 55,
        "z0_terreno": 0.30,
        "tipo_terreno": "valle_cordillera",
        "tipo_terreno_eolico": "quebrada_cordillera",
        "zona_climatica": "andes_sur",
        "riesgo_eolico": "alto",
        "requiere_autorizacion_dgac": True,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
    },
    "mantos_blancos_rajo": {
        "sitio_id": "mantos_blancos_rajo",
        "nombre": "Mantos Blancos · Rajo",
        "region": "Antofagasta",
        "operador": "METGO demo",
        "lat": -23.43,
        "lon": -70.06,
        "altitud_msnm": 1100,
        "altura_pluma_m": 55,
        "z0_terreno": 0.15,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "precordillera",
        "riesgo_eolico": "moderado",
        "requiere_autorizacion_dgac": False,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
        "faena_id": "mantos_blancos",
        "estacion_metgo": "mb_rajo",
    },
    "paipote_izaje": {
        "sitio_id": "paipote_izaje",
        "nombre": "Paipote · Izaje",
        "region": "Atacama",
        "operador": "METGO demo",
        "lat": -27.4064,
        "lon": -70.2853,
        "altitud_msnm": 810,
        "altura_pluma_m": 55,
        "z0_terreno": 0.12,
        "tipo_terreno": "rajo_minero",
        "tipo_terreno_eolico": "rajo_norte_grande",
        "zona_climatica": "precordillera",
        "riesgo_eolico": "moderado",
        "requiere_autorizacion_dgac": False,
        "area_carga_m2": 12.5,
        "coef_forma_cd": 1.2,
        "fuerza_limite_n": 25000,
        "faena_id": "paipote",
        "estacion_metgo": "paipote",
    },
}

ALIASES: dict[str, str] = {
    "qb": "quebrada_blanca",
    "quebrada": "quebrada_blanca",
    "doña_ines": "collahuasi",
    "dona_ines": "collahuasi",
    "cc": "cerro_colorado",
    "abra": "el_abra",
    "chuqui": "chuquicamata",
    "rt": "radomiro_tomic",
    "mh": "ministro_hales",
    "penon": "el_penon",
    "peñon": "el_penon",
    "coipa": "la_coipa",
    "pelambres": "los_pelambres",
    "bronces": "los_bronces",
    "teniente": "el_teniente",
    "mantos": "mantos_blancos_rajo",
    "mantos_blancos": "mantos_blancos_rajo",
    "mb_rajo": "mantos_blancos_rajo",
    "paipote": "paipote_izaje",
}


def normalizar_sitio_id(raw: str | None) -> str | None:
    key = (raw or "").strip().lower().replace("-", "_").replace(" ", "_")
    if not key:
        return None
    if key in SITIOS_GRUA:
        return key
    return ALIASES.get(key)


def _enrich(sitio: dict[str, Any]) -> dict[str, Any]:
    """Agrega parámetros ISA / GF / umbral equivalente al dict del sitio."""
    out = dict(sitio)
    alt = float(out.get("altitud_msnm") or 0)
    try:
        from api_rest.spati.high_altitude_engine import HighAltitudeEngine

        ha = HighAltitudeEngine()
        out.update(ha.parametros_sitio(alt))
        out["gust_factor"] = ha.factor_rafaga_terreno(
            str(out.get("tipo_terreno_eolico") or out.get("tipo_terreno") or "rajo_minero"),
            str(out.get("zona_climatica") or "altiplano"),
        )
        out["alta_montana"] = alt > 1500
    except Exception:
        out["alta_montana"] = alt > 1500
    return out


def get_sitio(sitio_id: str | None) -> dict[str, Any] | None:
    nid = normalizar_sitio_id(sitio_id)
    if not nid:
        return None
    return _enrich(SITIOS_GRUA[nid])


def listar_sitios(*, solo_alta_montana: bool = False) -> list[dict[str, Any]]:
    out = []
    for s in SITIOS_GRUA.values():
        if solo_alta_montana and s.get("operador") == "METGO demo":
            continue
        out.append(_enrich(s))
    return sorted(out, key=lambda x: (x.get("region") or "", x.get("nombre") or ""))
