-- S2: sitio spati + reglas remaining faenas alta montaña

insert into public.sitios (slug, nombre, region, dominio, estado, primary_color, center_lat, center_lon, modules)
values (
  'spati',
  'METGO SPATI Izaje',
  'Chile · 17 faenas alta montaña',
  'izaje',
  'activo',
  '#3b82f6',
  -24.25,
  -69.05,
  '["spati", "operaciones", "alertas"]'::jsonb
)
on conflict (slug) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  dominio = excluded.dominio,
  estado = excluded.estado,
  primary_color = excluded.primary_color,
  center_lat = excluded.center_lat,
  center_lon = excluded.center_lon,
  modules = excluded.modules;

insert into public.faena_reglas (faena, sistema, enabled, plan_minimo, config)
values
  ('quebrada_blanca', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('quebrada_blanca', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('quebrada_blanca', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('quebrada_blanca', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('cerro_colorado', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('cerro_colorado', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('cerro_colorado', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('cerro_colorado', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('el_abra', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('el_abra', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('el_abra', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('el_abra', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('chuquicamata', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('chuquicamata', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('chuquicamata', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('chuquicamata', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('radomiro_tomic', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('radomiro_tomic', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('radomiro_tomic', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('radomiro_tomic', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('ministro_hales', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('ministro_hales', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('ministro_hales', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('ministro_hales', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('spence', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('spence', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('spence', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('spence', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('el_penon', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('el_penon', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('el_penon', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('el_penon', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('la_coipa', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('la_coipa', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('la_coipa', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('la_coipa', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('maricunga', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('maricunga', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('maricunga', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('maricunga', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('candelaria', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('candelaria', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('candelaria', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('candelaria', 'ops', true, 'pro', '{"tabs":["umbrales"]}'),
  ('los_pelambres', 'izaje', true, 'trial', '{"tabs":["panel"]}'),
  ('los_pelambres', 'ambiente', true, 'trial', '{"tabs":["ambiente"]}'),
  ('los_pelambres', 'dron', true, 'starter', '{"tabs":["dron"]}'),
  ('los_pelambres', 'ops', true, 'pro', '{"tabs":["umbrales"]}')
on conflict (faena, sistema) do nothing;
